services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3005:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=__HOMEPAGE_ALLOWED_HOSTS__
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
